spring.application.name=todo-in-memory
spring.mvc.contentnegotiation.favor-parameter=true
# This setting supports PATCH method as the todo-client module implements in the ToDoRestClient class
spring.mvc.hiddenmethod.filter.enabled=true

