spring.application.name=todo-simple-security
# JPA
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
# H2-Console: http://localhost:8080/h2-console
# jdbc:h2:mem:testdb
spring.h2.console.enabled=true
# REST-API
spring.data.rest.base-path=/api
# Overriding credential for accessing endpoints
spring.security.user.name=apress
spring.security.user.password=springboot2
spring.security.user.roles=ADMIN,USER
# The way to get the _csrf.token value in Mustache template. Spring Boot 3.x.x needs to add the servlet tag
spring.mustache.servlet.expose-request-attributes=true