spring.application.name=todo-jms
# JPA
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create-drop
# ToDo JMS
todo.jms.destination=toDoDestination
#TODO Para evitar el error del esquema de transporte no reconocido, debes agregar la propiedad para la conexión de ActiveMQ
spring.activemq.broker-url=vm://localhost
spring.activemq.in-memory=true
spring.activemq.packages.trust-all=true
