spring.application.name=todo-mongo
# This setting supports PATCH method as the todo-client module implements in the ToDoRestClient class
spring.mvc.hiddenmethod.filter.enabled=true
# MongoDB
#spring.data.mongodb.port=27017
#spring.data.mongodb.host=localhost
#spring.data.mongodb.username=myuser
#spring.data.mongodb.password=mypassword
#spring.data.mongodb.database=todo
