spring.application.name=todo-redis
# JPA
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create-drop
# ToDo Redis
todo.redis.topic=todos
todo.redis.port=6379

# To run succesfully the applicatino with Redis using Docker are:
# docker run --name some-redis -d -p 6379:6379 redis
# docker exec -it some-redis redis-cli
# Once that done, in the Redis' shell issue the command: SUBSCRIBE todos
