spring.application.name=todo-websocket

# JPA
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create-drop

# Rest Repositories
spring.data.rest.base-path=/api

# WebSocket
todo.ws.endpoint=/stomp
todo.ws.broker=/todo
todo.ws.app=/todo-api-ws

# Example of curl command to test the application. As you issue this sort of command, the web app is updated automatically.
#curl -X POST -d '{"description":"New Task from curl"}' -H "Content-Type: application/json" http://localhost:8080/api/toDos