spring.application.name=todo-actuator
# This setting exposures all the endpints (due to wildcard '*'). This was changed in Spring Boot 2.5.0; for further details see:
# https://stackoverflow.com/questions/67893857/actuator-info-endpoint-not-working-with-spring-boot-2-5-0
management.endpoints.web.exposure.include=*
# This setting allows seeing the environment info in the endpoint /actuator/info
management.info.env.enabled = true
# It is necessary to manually expose the data info you want in this way for the endpoint /actuator/info
info.application.name=${spring.application.name}
info.developer.name=Incredible developer
info.developer.email=incredible@example.com
# The old version management.endpoint.shutdown.enabled=true is deprecated, instead you should use the following:
management.endpoint.shutdown.access=unrestricted
# If you wnat to see another system's health details, add the following line:
management.endpoint.health.show-details=always


management.endpoint.prometheus.enabled=true
management.prometheus.metrics.export.enabled=true

# To test the toDoHealthCheck successfully, it is necessary to set a valid location
todo.path=C:\\tmp\\todo